export const API_ERROR_CODE = {
  AUTH_EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  SERVICE_NOT_READY: "SERVICE_NOT_READY",
  VALIDATION_ERROR: "VALIDATION_ERROR"
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];

const API_ERROR_CODES = new Set<string>(Object.values(API_ERROR_CODE));

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === "string" && API_ERROR_CODES.has(value);
}
