export const API_ERROR_CODE = {
  ATTACHMENT_CONTENT_REJECTED: "ATTACHMENT_CONTENT_REJECTED",
  ATTACHMENT_QUOTA_EXCEEDED: "ATTACHMENT_QUOTA_EXCEEDED",
  ATTACHMENT_STORAGE_UNAVAILABLE: "ATTACHMENT_STORAGE_UNAVAILABLE",
  ATTACHMENT_TOO_LARGE: "ATTACHMENT_TOO_LARGE",
  ATTACHMENT_UPLOAD_IN_PROGRESS: "ATTACHMENT_UPLOAD_IN_PROGRESS",
  AUTH_EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT",
  AUTH_PASSWORD_POLICY_VIOLATION: "AUTH_PASSWORD_POLICY_VIOLATION",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  AUTHORIZATION_DENIED: "AUTHORIZATION_DENIED",
  GOOGLE_LOGIN_FAILED: "GOOGLE_LOGIN_FAILED",
  GOOGLE_OAUTH_NOT_CONFIGURED: "GOOGLE_OAUTH_NOT_CONFIGURED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_TASK_TRANSITION: "INVALID_TASK_TRANSITION",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_REQUEST_ORIGIN: "INVALID_REQUEST_ORIGIN",
  RATE_LIMITED: "RATE_LIMITED",
  REFRESH_CONCURRENCY_CONFLICT: "REFRESH_CONCURRENCY_CONFLICT",
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  SERVICE_NOT_READY: "SERVICE_NOT_READY",
  VALIDATION_ERROR: "VALIDATION_ERROR"
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];

const API_ERROR_CODES = new Set<string>(Object.values(API_ERROR_CODE));

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === "string" && API_ERROR_CODES.has(value);
}
